# build environment
FROM node:13.12.0-alpine as built-application
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
COPY . ./
RUN npm run build:dist

# production environment
FROM nginx:stable-alpine
COPY --from=built-application /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]