# build environment
# FROM node:13.12.0-alpine
# WORKDIR /app
# ENV PATH /app/node_modules/.bin:$PATH
# COPY mock ./mock
# RUN npm i -g json-server
# EXPOSE 3000
# RUN json-server --watch ./mock/db.json


FROM node:13.12.0-alpine
WORKDIR /app
RUN npm install -g json-server
ENV PATH /app/node_modules/.bin:$PATH
COPY mock ./mock
EXPOSE 3000
CMD json-server -H 0.0.0.0 --watch /app/mock/db.json